### ISSUE TITLE
Feedback on README and min/max

### ISSUE THREAD

**Issue by csymeonides** [drew-y/schemer-js#1]
Hey, nice job! A couple of things I noticed in your README:
- Your validation pass and fail examples are using the same input: {hello:"world"}
- Can you call min, max and regex directly or do you need rules.min, rules.max, rules.regex? (you've used both ways) 
- If I use rule min(5) then I would expect 5 to be a valid value, but your code uses a < comparison so it would fail. Same for max. 
- In your min and max examples I think it would actually be clearer if you called the functions atLeastFive and atMostFive. 
- It would be helpful if you could explain the differences between object and json types, and also what the math type is

**Comment by drew-y** [comment]
Thanks for your feedback! I've gone through and fixed all my examples. Thanks for pointing that out. I also agree that min and max should be using >= and <= comparison operators. So I fixed that with commit bcc7c16.

As for what the "json" and "math" type are. They are actually literally just the built in javascript JSON and Math functions. This is just how the special [toType](https://javascriptweblog.wordpress.com/2011/08/08/fixing-the-javascript-typeof-operator/) function works. So you'd never actually use this type unless you wanted the object property to actually be the whole JSON implementation. I can see how this could be confusing so I may just take it out of the list of valid types.
