### ISSUE TITLE
Proper way to check subobject

### ISSUE THREAD

**Issue by Rick83600** [drew-y/schemer-js#2]
Hey nice lib !

I have a question, what's the proper way to check suboject like: 

`{
  "details": {
    "type": "object",
    "lastname": "string",
    "firstname": "string"
  }
}`

Want to check details is an object and lastname & firstname is string.

Thanks

**Comment by drew-y** [comment]
All you'd need to do is something like this: 

``` javascript
{
  details: new Schema({
    lastname: "string",
    firstname: "string"
  }),
}
```

Hope that helps!

**Edit:** I should note that the above example is using shorthand syntax. You could also do it like this:

``` javascript
{
  details: {
    type: new Schema({lastname: "string", firstname: "string"}),
  },
}
```

**Comment by Rick83600** [comment]
Perfect ! 

Thanks a lot.
